import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // Prevent caching in development
  ...(process.env.NODE_ENV === 'development' && {
    other: {
      'Cache-Control': 'no-cache, no-store, must-revalidate',
      'Pragma': 'no-cache',
      'Expires': '0',
    },
  }),
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Prevent caching in development */}
        {process.env.NODE_ENV === 'development' && (
          <>
            <meta httpEquiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
            <meta httpEquiv="Pragma" content="no-cache" />
            <meta httpEquiv="Expires" content="0" />
          </>
        )}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        {/* Auto-detect build changes and clear cache */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                // Build timestamp - updated on each build
                const BUILD_TIME = ${Date.now()};
                const STORAGE_KEY = 'app_build_time';
                
                // Clear service worker cache if exists
                if (typeof window !== 'undefined' && 'serviceWorker' in navigator) {
                  navigator.serviceWorker.getRegistrations().then(function(registrations) {
                    for(let registration of registrations) {
                      registration.unregister();
                    }
                  });
                }
                
                // Check if this is a new build
                if (typeof window !== 'undefined' && typeof Storage !== 'undefined') {
                  const lastBuildTime = localStorage.getItem(STORAGE_KEY);
                  
                  if (lastBuildTime && parseInt(lastBuildTime) !== BUILD_TIME) {
                    // New build detected - clear all caches and reload
                    console.log('New build detected! Clearing cache and reloading...');
                    
                    // Clear localStorage and sessionStorage
                    localStorage.clear();
                    sessionStorage.clear();
                    
                    // Clear all caches
                    if ('caches' in window) {
                      caches.keys().then(function(names) {
                        for (let name of names) {
                          caches.delete(name);
                        }
                      });
                    }
                    
                    // Force reload after a short delay
                    setTimeout(function() {
                      window.location.reload(true);
                    }, 100);
                  } else {
                    // Store current build time
                    localStorage.setItem(STORAGE_KEY, BUILD_TIME.toString());
                  }
                }
                
                // In development, disable cache for fetch requests
                if (typeof window !== 'undefined' && typeof fetch !== 'undefined') {
                  const isDev = window.location.hostname === 'localhost' || 
                                window.location.hostname === '127.0.0.1' ||
                                window.location.hostname.includes('localhost');
                  
                  if (isDev) {
                    const originalFetch = window.fetch;
                    window.fetch = function(...args) {
                      const [url, options = {}] = args;
                      return originalFetch(url, {
                        ...options,
                        cache: 'no-store',
                        headers: {
                          ...options.headers,
                          'Cache-Control': 'no-cache',
                        },
                      });
                    };
                  }
                }
              })();
            `,
          }}
        />
      </body>
    </html>
  );
}
